package com.example.network.utils

object Constants {
    const val SORT_FIELD = "sortField"
    const val SORT_TYPE = "sortType"
    const val PAGE_FIELD = "page"
    const val MOVIE_ID_FIELD = "movieId"
    const val DATE_FIELD = "date"
    const val TYPE_FIELD = "type"
    const val LIMIT_FIELD = "limit"
    const val SELECT_FILED = "selectFields"
    const val QUERY_FIELD = "query"
    const val PERSON_ID_FIELD = "personId"
    const val NOM_AWARD_YEAR_FIELD = "nomination.award.year"
    const val NOM_AWARD_TITLE_FIELD = "nomination.award.title"
    const val COUNT_AWARDS_FIELD = "countAwards"
    const val PERSONS_ID_FIELD = "persons.id"
    const val NAME_FIELD = "name"
    const val TITLE_FIELD = "title"
    const val RATING_KP_FIELD = "rating.kp"
    const val GENRES_NAME_FIELD = "genres.name"
    const val COUNTRIES_NAME_FIELD = "countries.name"
    const val LISTS_FIELD = "lists"
    const val CATEGORY_FIELD = "category"
    const val SLUG_FIELD = "slug"
    const val MOVIES_RATING_FIELD = "movies.rating"
    const val NOT_NULL_FIELD = "notNullFields"
    const val PHOTO_FIELD = "photo"
    const val PROFESSION_VALUE = "profession.value"
    const val IS_SERIES_FIELD = "isSeries"
    const val VOTES_KP_FIELD = "votes.kp"
    const val YEAR_FIELD = "year"
    const val NETWORK_ITEMS_NAME = "networks.items.name"

    const val SORT_ASC = "1"
    const val SORT_DESC = "-1"
    const val TRUE = "true"
    const val FALSE = "false"

    const val POSITIVE_VALUE = "Позитивный"
    const val NEGATIVE_VALUE = "Негативный"
    const val NEUTRAL_VALUE = "Нейтральный"

    const val LAST_YEAR = 1888
}